//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSqlRules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSqlRules.RuleResources", typeof(RuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create ResourceManager for {0} from {1}..
        /// </summary>
        internal static string CannotCreateResourceManager {
            get {
                return ResourceManager.GetString("CannotCreateResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Primary Key was found in {0}..
        /// </summary>
        internal static string SRD0001_ProblemDescription {
            get {
                return ResourceManager.GetString("SRD0001_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table does not have Primary Key.
        /// </summary>
        internal static string SRD0001_RuleName {
            get {
                return ResourceManager.GetString("SRD0001_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-alphanumeric Table name was found in {0}..
        /// </summary>
        internal static string SRN0001_ProblemDescription {
            get {
                return ResourceManager.GetString("SRN0001_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table does not meet naming convention.
        /// </summary>
        internal static string SRN0001_RuleName {
            get {
                return ResourceManager.GetString("SRN0001_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-alphanumeric Column name was found in {0}..
        /// </summary>
        internal static string SRN0002_ProblemDescription {
            get {
                return ResourceManager.GetString("SRN0002_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name does not meet naming convention.
        /// </summary>
        internal static string SRN0002_RuleName {
            get {
                return ResourceManager.GetString("SRN0002_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-alphanumeric View name was found in {0}..
        /// </summary>
        internal static string SRN0003_ProblemDescription {
            get {
                return ResourceManager.GetString("SRN0003_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View does not meet naming convention.
        /// </summary>
        internal static string SRN0003_RuleName {
            get {
                return ResourceManager.GetString("SRN0003_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-alphanumeric Trigger name was found in {0}..
        /// </summary>
        internal static string SRN0004_ProblemDescription {
            get {
                return ResourceManager.GetString("SRN0004_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger does not meet naming convention.
        /// </summary>
        internal static string SRN0004_RuleName {
            get {
                return ResourceManager.GetString("SRN0004_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-alphanumeric Stored Procedure name was found in {0}..
        /// </summary>
        internal static string SRN0005_ProblemDescription {
            get {
                return ResourceManager.GetString("SRN0005_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedure does not meet naming guidelines.
        /// </summary>
        internal static string SRN0005_RuleName {
            get {
                return ResourceManager.GetString("SRN0005_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-alphanumeric User Function name was found in {0}..
        /// </summary>
        internal static string SRN0006_ProblemDescription {
            get {
                return ResourceManager.GetString("SRN0006_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Function does not meet naming convention.
        /// </summary>
        internal static string SRN0006_RuleName {
            get {
                return ResourceManager.GetString("SRN0006_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word VIEW was found in {0}..
        /// </summary>
        internal static string SRN0007_ProblemDescription {
            get {
                return ResourceManager.GetString("SRN0007_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using view in table names..
        /// </summary>
        internal static string SRN0007_RuleName {
            get {
                return ResourceManager.GetString("SRN0007_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITFOR DELAY statement was found in {0}..
        /// </summary>
        internal static string SRP0001_ProblemDescription {
            get {
                return ResourceManager.GetString("SRP0001_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using WaitFor Delay statements in stored procedures, functions and triggers..
        /// </summary>
        internal static string SRP0001_RuleName {
            get {
                return ResourceManager.GetString("SRP0001_RuleName", resourceCulture);
            }
        }
    }
}
